import assert from 'node:assert/strict';
import { defaultDraft } from '@/data/presets';
import { createBlankSnapshot } from '@/lib/guided-builder';
import { addCastMember, memberDraft, PERSON_CUSTOM_KEYS, PERSON_FIELDS, selectCastMember, setCastEnabled, syncCast } from '@/lib/character-cast';
import { castChecks, duplicatePerson, OUTFIT_FIELDS, personTemplate, randomizePeople, resetPeople, transferPersonFields } from '@/lib/cast-workflow';
import { buildCastPromptParts, generatePrompts, formatProfileOutput } from '@/lib/prompt-engine';
import { prepareShareSnapshot, shareCustomEntries } from '@/lib/share-snapshot';
import { createEmptyNoteWorkspace, parsePersonNotes } from '@/lib/inference/note-workspace';
import { exportStudioBackup, parseStudioBackup } from '@/lib/studio-backup';
import { DEFAULT_STUDIO_PREFERENCES, hydrateDraft, parsePresets } from '@/lib/storage';
import { diffSnapshots } from '@/lib/character-insights';

let group = setCastEnabled({ draft: hydrateDraft(defaultDraft), locks: { hairColors: true } }, true);
const first = group.draft.cast!.members[0].id;
const second = group.draft.cast!.members[1].id;
group.draft.custom.expression = 'EXPRESSION-FIRST';
group.draft.custom.pose = 'POSE-FIRST';
group.draft.custom.action = 'LEGACY-MIXED';
group.draft.cast!.members[0].nameEn = 'PRIVATE-LABEL';
group.draft.cast!.relationshipNote = 'PRIVATE-RELATION';
group.draft.cast!.interaction = 'talking';
group = syncCast(group);
const output = generatePrompts(group.draft);
assert.ok(output.en.includes('EXPRESSION-FIRST'));
assert.ok(output.en.includes('LEGACY-MIXED'));
assert.ok(!output.en.includes('POSE-FIRST'));
assert.equal(group.draft.custom.pose, 'POSE-FIRST', 'suppressed pose is retained');
assert.ok(output.en.includes('PRIVATE-LABEL'));
const shared = prepareShareSnapshot(group);
assert.ok(!JSON.stringify(shared).includes('PRIVATE-'));
const opted = prepareShareSnapshot(group, [`cast:${first}:custom:expression`]);
const parts = buildCastPromptParts(opted.draft);
assert.ok(parts.individual[0].en.includes('EXPRESSION-FIRST'));
assert.ok(!parts.individual[1].en.includes('EXPRESSION-FIRST'), 'opted-in text never bleeds into another person');
assert.ok(!parts.common.en.includes('EXPRESSION-FIRST'));
assert.ok(shareCustomEntries(group, 'en').some((entry) => entry.label.includes('English label')));
assert.equal(hydrateDraft(group.draft).cast!.members[0].nameEn, 'PRIVATE-LABEL');
assert.equal(hydrateDraft(group.draft).cast!.relationshipNote, 'PRIVATE-RELATION');
const reset = resetPeople(group, 'person');
assert.deepEqual(reset.draft.cast!.members[1], group.draft.cast!.members[1]);
assert.equal(reset.draft.background, group.draft.background);
assert.equal(reset.draft.cast!.members[0].nameEn, 'PRIVATE-LABEL');
assert.ok(PERSON_FIELDS.every((field) => Array.isArray(reset.draft[field]) ? reset.draft[field].length === 0 : reset.draft[field] === ''));
assert.ok(PERSON_CUSTOM_KEYS.every((key) => !reset.draft.custom[key]));
assert.equal(reset.locks.hairColors, undefined);
const resetAll = resetPeople(group, 'people');
assert.equal(castChecks(resetAll).filter((check) => check.id.startsWith('empty-')).length, 2);
assert.ok(castChecks(group).some((check) => check.personId === second));
const duplicate = duplicatePerson(group);
assert.equal(duplicate.draft.cast!.members.length, 3);
assert.notEqual(duplicate.draft.cast!.activeId, first);
assert.deepEqual(duplicate.draft.hairColors, group.draft.hairColors);
assert.equal(duplicate.locks.hairColors, true);
const random = randomizePeople(group, [second]);
assert.deepEqual(random.draft.cast!.members[0], group.draft.cast!.members[0]);
assert.equal(random.draft.background, group.draft.background);
assert.equal(random.draft.cast!.activeId, first);
assert.deepEqual(random.draft.cast!.members[1].fields.faceFeatures, []);
const outfitSource = { ...createBlankSnapshot(), draft: { ...createBlankSnapshot().draft, outfit: 'suit', custom: { outfit: 'OUTFIT-ONLY' } } };
const transferred = transferPersonFields(group, outfitSource, OUTFIT_FIELDS, ['outfit']);
assert.deepEqual(transferred.draft.hairColors, group.draft.hairColors);
assert.equal(transferred.draft.background, group.draft.background);
assert.deepEqual(transferred.draft.cast!.members[1], group.draft.cast!.members[1]);
assert.equal(transferred.draft.custom.expression, 'EXPRESSION-FIRST');
assert.equal(transferred.draft.custom.outfit, 'OUTFIT-ONLY');
const lockedTransfer = transferPersonFields({ ...group, locks: { ...group.locks, outfit: true } }, outfitSource, OUTFIT_FIELDS, []);
assert.equal(lockedTransfer.draft.outfit, group.draft.outfit);
const template = personTemplate(group, 'outfit');
assert.equal(template.draft.cast, undefined);
assert.equal(template.draft.background, '');
assert.deepEqual(template.draft.hairColors, []);
const notes = { [first]: { ...createEmptyNoteWorkspace(), note: 'FIRST-NOTE' }, [second]: { ...createEmptyNoteWorkspace(), note: 'SECOND-NOTE' } };
const restored = parseStudioBackup(exportStudioBackup({ current: group, presets: [], history: [], randomHistory: [], preferences: DEFAULT_STUDIO_PREFERENCES, noteWorkspace: { ...createEmptyNoteWorkspace(), note: 'SHARED-NOTE' }, personNotes: notes, editorMode: 'note' }))!;
assert.deepEqual(restored.personNotes, notes);
assert.equal(restored.noteWorkspace.note, 'SHARED-NOTE');
assert.deepEqual(parsePersonNotes({ constructor: createEmptyNoteWorkspace(), bad: 'invalid' }), {});
const named = { ...group, draft: { ...group.draft, cast: { ...group.draft.cast!, relationshipNote: 'CHANGED' } } };
assert.ok(diffSnapshots(group, named).some((change) => change.id === 'cast-relationship-note'));
const countConflict = syncCast({ ...group, draft: { ...group.draft, custom: { ...group.draft.custom, character: 'exactly 3 people' } } });
assert.ok(castChecks(countConflict).some((check) => check.id === 'custom-count'));
const briefDraft = { ...group.draft, custom: { ...group.draft.custom, must: 'MUST-X', preference: 'PREFER-Y' } };
const brief = formatProfileOutput(generatePrompts(briefDraft), briefDraft, 'human-brief').combined;
assert.ok(brief.includes('人数：2人') && brief.includes('必須：MUST-X') && brief.includes('希望（可能なら）：PREFER-Y'));
assert.equal(parsePresets(JSON.stringify([{ id: 'template', name: 'v2', snapshot: template, scope: 'outfit', note: 'winter' }]))[0].scope, 'outfit');
assert.equal(memberDraft(group.draft, { ...group.draft.cast!.members[1], custom: {} }).custom.expression, '', 'missing person text never inherits the active person’s text');
assert.notEqual(addCastMember(group).draft.cast!.activeId, addCastMember(group).draft.cast!.activeId);
assert.equal(selectCastMember(group, second).draft.custom.expression, '');
console.log('Cast workflow checks passed: scoped reset/copy, isolated notes, privacy, expressions, templates, and review.');
