import assert from 'node:assert/strict';
import { defaultDraft } from '@/data/presets';
import { addCastMember, castRandomLocks, MAX_CAST_MEMBERS, removeCastMember, selectCastMember, setCastEnabled, syncCast } from '@/lib/character-cast';
import { generateStudioPrompts } from '@/lib/prompt-blocks';
import { formatProfileOutput } from '@/lib/prompt-engine';
import { hydrateDraft, migrateSnapshot, parseSnapshot, encodeShareSnapshot, decodeShareSnapshot } from '@/lib/storage';
import { prepareShareSnapshot, shareCustomEntries } from '@/lib/share-snapshot';
import { diffSnapshots } from '@/lib/character-insights';
import { randomizeAll } from '@/lib/random-engine';
import { createEditorTimeline, commitEditorTimeline, undoEditorTimeline } from '@/lib/editor-timeline';
import { stylePresets } from '@/data/style-presets';
import { emptyStylePack } from '@/lib/style-pack';
import { DEFAULT_STUDIO_PREFERENCES } from '@/lib/storage';
import { exportStudioBackup, parseStudioBackup } from '@/lib/studio-backup';
import { createEmptyNoteWorkspace } from '@/lib/inference/note-workspace';

const legacy = { draft: hydrateDraft(defaultDraft), locks: { hairColors: true } };
const original = JSON.stringify(legacy);
let group = setCastEnabled(legacy, true);
assert.notEqual(group.draft.cast!.activeId, setCastEnabled(legacy, true).draft.cast!.activeId, 'new casts use unique IDs so note drafts cannot attach to a different person');
group = { ...group, draft: { ...group.draft, cast: { ...group.draft.cast!, activeId: 'person-1', members: group.draft.cast!.members.map((member, index) => ({ ...member, id: `person-${index + 1}` })) } } };
assert.equal(group.draft.cast!.members.length, 2);
assert.equal(JSON.stringify(legacy), original, 'enable does not mutate legacy input');
group.draft.hairColors = ['black'];
group.draft.custom.character = 'PRIVATE-FIRST';
group = syncCast(group);
group.draft.cast!.members[0].name = 'SECRET-NAME';
group = selectCastMember(group, 'person-2');
assert.deepEqual(group.draft.hairColors, [], 'new person starts blank');
assert.equal(group.locks.hairColors, undefined);
group.draft.hairColors = ['white'];
group.draft.gender = 'female';
group.draft.custom.character = 'PRIVATE-SECOND';
group.draft.negatives = ['one-person', 'no-people', 'no-text'];
group = syncCast(group);
const second = JSON.stringify(group.draft.cast!.members[1]);
const firstAgain = selectCastMember(group, 'person-1');
assert.deepEqual(firstAgain.draft.hairColors, ['black']);
assert.equal(firstAgain.draft.custom.character, 'PRIVATE-FIRST');
assert.equal(firstAgain.locks.hairColors, true);
assert.deepEqual(parseSnapshot(JSON.stringify(group)), JSON.parse(JSON.stringify(group)), 'reload preserves all people');
assert.deepEqual(decodeShareSnapshot(encodeShareSnapshot(group)), JSON.parse(JSON.stringify(group)), 'share codec preserves group');
assert.equal(migrateSnapshot(legacy)?.draft.cast, undefined);
const output = generateStudioPrompts(group.draft);
assert.ok(output.positiveEn.includes('Exactly 2 distinct characters'));
assert.ok(output.positiveEn.includes('[Person 1 (SECRET-NAME) — left side'));
assert.ok(output.positiveEn.includes('[Person 2 — right side'));
assert.ok(output.positiveEn.includes('black hair'));
assert.ok(output.positiveEn.includes('white hair'));
assert.ok(!output.negativeEn.includes('Exactly one character'));
assert.ok(!output.negativeJa.includes('人物なし'));
for (const mode of ['ja', 'en', 'both', 'short', 'tags'] as const) assert.ok(output[mode].includes('2'), mode);
for (const profile of ['generic', 'stable-diffusion', 'midjourney', 'novelai', 'human-brief'] as const) {
  const exported = formatProfileOutput(output, group.draft, profile);
  assert.ok(exported.combined.includes('Person 2') || exported.combined.includes('人物2'));
  assert.ok(!exported.negative.includes('multiple characters'));
}
const noCustom = prepareShareSnapshot(group);
assert.ok(!JSON.stringify(noCustom).includes('PRIVATE'));
assert.ok(!JSON.stringify(noCustom).includes('SECRET'));
assert.ok(noCustom.draft.cast!.members.every((member) => Object.keys(member.locks).length === 0));
assert.ok(shareCustomEntries(group).some((entry) => entry.value === 'PRIVATE-FIRST'));
const optedIn = prepareShareSnapshot(group, ['cast:person-1:name', 'cast:person-2:custom:character']);
assert.ok(JSON.stringify(optedIn).includes('SECRET-NAME'));
assert.ok(JSON.stringify(optedIn).includes('PRIVATE-SECOND'));
assert.ok(!JSON.stringify(optedIn).includes('PRIVATE-FIRST'));
const single = setCastEnabled(group, false);
assert.ok(!generateStudioPrompts(single.draft).en.includes('PRIVATE-FIRST'));
assert.equal(prepareShareSnapshot(single).draft.cast, undefined, 'single share excludes retained people');
assert.equal(generateStudioPrompts(setCastEnabled(single, true).draft).en, output.en);
const randomized = syncCast({ draft: randomizeAll(firstAgain.draft, castRandomLocks(firstAgain.draft, firstAgain.locks), undefined, [], () => 0.6), locks: firstAgain.locks });
assert.equal(JSON.stringify(randomized.draft.cast!.members[1]), second, 'random keeps other people');
assert.equal(randomized.draft.background, firstAgain.draft.background);
assert.deepEqual(randomized.draft.hairColors, ['black']);
assert.deepEqual(randomized.draft.faceFeatures, []);
let large = group;
for (let index = 0; index < 10; index++) large = addCastMember(large);
assert.equal(large.draft.cast!.members.length, MAX_CAST_MEMBERS);
const removed = removeCastMember(large, large.draft.cast!.activeId);
assert.equal(removed.draft.cast!.members.length, MAX_CAST_MEMBERS - 1);
assert.ok(removed.draft.cast!.members.some((member) => member.id === removed.draft.cast!.activeId));
assert.ok(!generateStudioPrompts({ ...group.draft, purpose: 'background' }).en.includes('PRIVATE-FIRST'));
const edited = syncCast({ ...group, draft: { ...group.draft, hairColors: ['red'] } });
assert.ok(diffSnapshots(group, edited).some((change) => change.id === 'cast-person-2-field-hairColors'));
const timeline = commitEditorTimeline(createEditorTimeline(group), removed, { action: 'remove' });
assert.deepEqual(undoEditorTimeline(timeline).present.snapshot, JSON.parse(JSON.stringify(group)));
const malformed = hydrateDraft({ ...group.draft, cast: { ...group.draft.cast, members: [...group.draft.cast!.members, ...group.draft.cast!.members], activeId: 'missing' } });
assert.equal(malformed.cast!.members.length, 2, 'duplicate IDs rejected');
assert.equal(malformed.cast!.activeId, 'person-1');
const withGap = syncCast({ ...group, draft: { ...group.draft, generatedGap: { seedId: 'test', labelJa: 'テスト', labelEn: 'Test', segmentIndexes: [], changes: [] } } });
const clearedGap = syncCast({ ...withGap, draft: { ...withGap.draft, generatedGap: undefined } });
assert.equal(clearedGap.draft.cast!.members[1].generatedGap, undefined, 'clearing a gap clears the member copy');
const customExclusion = generateStudioPrompts({ ...legacy.draft, custom: { ...legacy.draft.custom, negatives: 'no horns' } });
assert.ok(customExclusion.negativeEn.toLowerCase().includes('horns'), 'custom negatives do not become positive concepts');
const interacting = { ...group.draft, cast: { ...group.draft.cast!, interaction: 'talking' } };
assert.ok(generateStudioPrompts(interacting).en.includes('talking together'));
assert.ok(!generateStudioPrompts(interacting).en.includes('Pose/action:'));
assert.equal(interacting.cast.members[0].fields.pose, group.draft.cast!.members[0].fields.pose, 'group action preserves individual poses');
const styled = generateStudioPrompts({ ...group.draft, stylePack: { ...emptyStylePack(), presetId: stylePresets[0].id } });
assert.ok(styled.blocks.includes('人物2'), 'style blocks include every person');
assert.ok(styled.blocks.includes('CONTENT'));
const backup = exportStudioBackup({ current: group, presets: [], history: [], randomHistory: [], preferences: DEFAULT_STUDIO_PREFERENCES, noteWorkspace: createEmptyNoteWorkspace(), editorMode: 'form' });
assert.deepEqual(parseStudioBackup(backup)?.current, JSON.parse(JSON.stringify(group)), 'full backup restores the entire cast');
console.log('Cast checks passed: per-person editing, 2–6 people, output, privacy, persistence, undo, locks, and legacy compatibility.');
